### ISSUE TITLE
jitter_z=False fails to constrain cells in 2D

### ISSUE THREAD

**Issue by odanieloliveira** [HaseloffLab/CellModeller#26] opened 2020-10-17 01:14 UTC
Dear all, I've recently started to use CellModeller for my Master's thesis project. I was able to install the master branch following Tim Rudge's instructions posted in the comment section of another issue. However, when trying to run Tutorial1a as well as my own models the cells are leaving the plane (growing in 3D) even though I have set jitter_z=False. Does anybody have the same issue and if so, is there any way to fix this?

Thanks in advance for your help and time.
Best regards,
Daniel

**Comment by avimanyu786** [comment] 2020-11-06 21:14
Apparently, if you keep the position of the initial cell at (0,0,0.5) and raise the default number of maximum cells to 20000, you can simulate cells in 2D quite conveniently, over ~12000 cells. I just tested this on a GeForce GTX 1050 Ti with 4GB video memory.
 
![image](https://user-images.githubusercontent.com/28894462/98414370-4090ff80-20a1-11eb-9660-c6320bc37923.png)
![image](https://user-images.githubusercontent.com/28894462/98414551-9796d480-20a1-11eb-9b63-0435e06472c0.png)

Please try experimenting with the following code(worked for the above screenshots):

```
import random
from CellModeller.Regulation.ModuleRegulator import ModuleRegulator
from CellModeller.Biophysics.BacterialModels.CLBacterium import CLBacterium
from CellModeller.GUI import Renderers
import numpy
import math

def setup(sim):
    # Set biophysics, signalling, and regulation models
    biophys = CLBacterium(sim, jitter_z=False, gamma = 20, max_planes=1, max_cells=20000)

    biophys.addPlane((0,0,0),(0,0,1),1.0) #Base plane
    #biophys.addPlane((10,0,0),(-1,0,0),1.0)
    #biophys.addPlane((-10,0,0),(1,0,0),1.0)
    #biophys.addPlane((0,10,0),(0,-1,0),1.0)
    #biophys.addPlane((0,-10,0),(0,1,0),1.0)

    # use this file for reg too
    regul = ModuleRegulator(sim, sim.moduleName)	
    # Only biophys and regulation
    sim.init(biophys, regul, None, None)
 
    # Specify the initial cell and its location in the simulation
    sim.addCell(cellType=0, pos=(0,0,0.5), dir=(1,0,0))

    # Add some objects to draw the models
    therenderer = Renderers.GLBacteriumRenderer(sim)
    sim.addRenderer(therenderer)
    sim.pickleSteps = 20

def init(cell):
    # Specify mean and distribution of initial cell size
    cell.targetVol = 3.0 + random.uniform(0.0,0.5)
    # Specify growth rate of cells
    cell.growthRate = 1.0
    cell.color = (0.0,1.0,0.0)

def update(cells):
    #Iterate through each cell and flag cells that reach target size for division
    for (id, cell) in cells.items():
        if cell.volume > cell.targetVol:
            cell.divideFlag = True

def divide(parent, d1, d2):
    # Specify target cell size that triggers cell division
    d1.targetVol = 3.0 + random.uniform(0.0,0.5)
    d2.targetVol = 3.0 + random.uniform(0.0,0.5)
```
It's a modified version of [Tutorial_1c.py](https://github.com/HaseloffLab/CellModeller/blob/master/Examples/Tutorial_1/Tutorial_1c.py). I've kept only the base plane and reduced `max_planes` to 1. Hope that helps.

**Comment by odanieloliveira** [comment] 2020-11-07 03:02
Dear Avimanyu,

First of all, thank you for your feedback! Following up on your comments, here's what I did:

- Try to replicate your result in my machine which I was able to do just by copying the code. Here are the screenshots:

<img width="1525" alt="Screenshot 2020-11-07 at 01 54 31" src="https://user-images.githubusercontent.com/73005620/98430311-65d33d00-20a4-11eb-987a-659f87fe5da1.png">

<img width="736" alt="Screenshot 2020-11-07 at 01 55 48" src="https://user-images.githubusercontent.com/73005620/98430324-6e2b7800-20a4-11eb-9f95-b27a1d8e0377.png">


- Inspired by the parameters you changed and since my initial report was regarding Tutorial_1a.py I modified Tutorial_1a.py to try to replicate the results. Firstly, by setting max_cells= 20 000 and adding just a base plane the cells grow in 2D until around 500 cells but then break out. Secondly, changing from pos=(0,0,0) to pos=(0,0,0.5) allowed the simulation to run smoothly in 2D up to around 9000 cells. The only difference between your modified version of Tutorial_1c.py and my modified version of Tutorial_1a.py seems to be the `cell.targetVol` which is set to 3.0 and 3.5 respectively. Please find the modified code as well as the screenshots below.

<img width="1507" alt="Screenshot 2020-11-07 at 02 34 07" src="https://user-images.githubusercontent.com/73005620/98430353-80a5b180-20a4-11eb-95d6-86e92d6b5ade.png">

<img width="739" alt="Screenshot 2020-11-07 at 02 34 20" src="https://user-images.githubusercontent.com/73005620/98430375-90bd9100-20a4-11eb-9414-2a915c177db6.png">

```
import random
from CellModeller.Regulation.ModuleRegulator import ModuleRegulator
from CellModeller.Biophysics.BacterialModels.CLBacterium import CLBacterium
from CellModeller.GUI import Renderers
import numpy
import math

def setup(sim):
    # Set biophysics module
    biophys = CLBacterium(sim, jitter_z=False, gamma = 20, max_planes=1, max_cells=20000)

    biophys.addPlane((0,0,0),(0,0,1),1.0) #Base plane

    # Set up regulation module
    regul = ModuleRegulator(sim, sim.moduleName)	
    # Only biophys and regulation
    sim.init(biophys, regul, None, None)
 
    # Specify the initial cell and its location in the simulation
    sim.addCell(cellType=0, pos=(0,0,0.5), dir=(1,0,0))

    # Add some objects to draw the models
    therenderer = Renderers.GLBacteriumRenderer(sim)
    sim.addRenderer(therenderer)
    
    # Specify how often data is saved
    sim.pickleSteps = 100

def init(cell):
    # Specify mean and distribution of initial cell size
    cell.targetVol = 3.5 + random.uniform(0.0,0.5)
    # Specify growth rate of cells
    cell.growthRate = 1.0
    cell.color = (0.0,1.0,0.0)

def update(cells):
    #Iterate through each cell and flag cells that reach target size for division
    for (id, cell) in cells.items():
        if cell.volume > cell.targetVol:
            cell.divideFlag = True

def divide(parent, d1, d2):
    # Specify target cell size that triggers cell division
    d1.targetVol = 3.5 + random.uniform(0.0,0.5)
    d2.targetVol = 3.5 + random.uniform(0.0,0.5)
```

Finally, since my own models require more flexibility in terms of the initial number of cells and their positional parameters, the best fix that I found and that I've been using for a while now is to add one base plane and a second plane on top to squeeze the cells and force them to grow in 2D. I've been going up to 10 000 cells or more and I didn't feel much increase in computational time (due to the increased number of contact calculations).
Anyway, it would still be interesting to sort out what's happening with jitter-z since I have a colleague who uses an older version of CellModeller and doesn't have the same issues. I'll try to take some time to figure it out and I'll keep you updated if I find any other solution.

**Comment by timrudge** [comment] 2020-11-09 10:42
Hi there - sorry for the delay. I am really not sure what the problem is here, but anyway I recommend you switch to the newer python 3 code found on the dev branch. To do this;

1. Clone the repo - git clone https://github.com/HaseloffLab/CellModeller.git
2. cd CellModeller
3. Checkout the branch - git checkout dev
4. Install the package - pip install -e .

You can then run the GUI - python Scripts/CellModellerGUI.py, or batch mode - python Scripts/batch.py <model file>

Let me know if you have any problems. 

best
Tim

**Comment by danieljonesiii** [comment] 2020-11-11 15:27
Hi,
I'm also experiencing the same issue as OP and have adopted odanieloliveira's workaround of adding a second plane. Just checked out the dev branch two days ago so it should be the latest version of the code.
best regards,
Daniel

**Comment by timrudge** [comment] 2020-11-11 15:29
You have the same problem on dev branch? I will look into this. You should not need planes, that will be inefficient…

**Comment by danieljonesiii** [comment] 2020-11-11 15:38
My command of git is unfortunately rather shaky but here is the output of git log, apologies if I'm on the wrong branch: 

`commit b896f3109387307b773960627c3656ba72bdcf6a (HEAD -> dev, origin/dev)
Author: Tim Rudge <timrudge@gmail.com>
Date:   Wed Jul 8 09:16:58 2020 -0400

    Add load geometry button to only load cell position, orientation, length. Not fully tested

commit 6c34ad45f149a0d6ae2365774ea43c3d583722b5
Author: Tim Rudge <timrudge@gmail.com>
Date:   Wed Jun 17 19:30:30 2020 -0400

    Correct rendering of signal grid, scaled to max

commit 58fc68cd8d70abee8846d7c344bb36f1ecd4c623
Author: Tim Rudge <timrudge@gmail.com>
Date:   Wed Jun 17 19:29:38 2020 -0400

    Fix saving of signals and species in pickles
`

**Comment by timrudge** [comment] 2020-11-16 20:31
Hi all - this is very strange, I can run the dev branch using Examples/ex1_simpleGrowth.py and it works fine. Did you do “pip install -e .” After switching to dev branch, and before running the example models?

**Comment by odanieloliveira** [comment] 2020-11-16 21:10
Hey everyone. I honestly haven't tried installing the dev branch since I'm getting closer to a deadline and I don't feel very comfortable doing those kinds of changes at this moment. 
Regardless, I've just tried running Examples/ex1_simpleGrowth.py on my machine with the version with which I first reported the issue, and, like Tim, I was able to run up to 20 000 cells without any z-axis movement. 
However, I must say I first noticed the issue on a model of my own, and then, as a test to rule out any issue unique to my model I ran Examples/Tutorial_1/Tutorial_1a.py and found the same problem which apparently is also happening in danieljones333's and avimanyu786's machines.
Tim, if it's not asking too much, could you please try running Examples/Tutorial_1/Tutorial_1a.py instead of Examples/ex1_simpleGrowth.py in your machine with the dev branch to see if the issue persists?

**Comment by timrudge** [comment] 2020-11-16 21:19
Sure. I ran it to about 1000 cells with the dev branch code and it remains 2D.

**Comment by odanieloliveira** [comment] 2020-11-16 21:53
So strange! But thanks, I just ran it as well up to 11000 cells and it seems to be working fine now! I'll try with one of my models as well.

**Comment by danieljones333** [comment] 2020-11-17 10:49
Just to be safe I created a fresh conda environment, re-cloned the git repository, switched to dev branch, and re-installed, but I'm still having issues. (I've also tried running the code on another machine, as well as running the code from a docker container  as described [here](https://hub.docker.com/r/avimanyu786/cellmodeller), with similar results.) 

For instance, here is what it looks like after running Examples/Tutorial_1/Tutorial_1a.py on my laptop for 200 steps:
![step-00200_cropped](https://user-images.githubusercontent.com/8205432/99378214-7915b200-28c7-11eb-87fd-012e0762a929.png)

I should add that the problems seem to go deeper than undesired z axis movement. When running Examples/Tutorial_1/Tutorial_1a.py using the Scripts/batch.py script, the simulation usually fails anywhere between 10 and ~100s of cells. Here are the tracebacks from two independent runs of Tutorial_1a.py: 

```
200    32 cells      54 cts       7 iterations  residual = 0.004056
Traceback (most recent call last):
  File "/home/daniel/djl/code/CellModeller/Scripts/batch.py", line 54, in <module>
    main()
  File "/home/daniel/djl/code/CellModeller/Scripts/batch.py", line 50, in main
    simulate(moduleName, platnum, devnum)
  File "/home/daniel/djl/code/CellModeller/Scripts/batch.py", line 18, in simulate
    sim.step()
  File "/home/daniel/djl/code/CellModeller/CellModeller/Simulator.py", line 360, in step
    while not self.phys.step(self.dt): #neighbours are current here
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 569, in step
    if self.progress():
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 536, in progress
    if self.tick(self.actual_dt):
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 601, in tick
    self.sub_tick_init(dt)
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 590, in sub_tick_init
    self.sort_cells()
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 755, in sort_cells
    self.sq_inds.put(numpy.arange(self.n_sqs), numpy.searchsorted(sorted_sqs, numpy.arange(self.n_sqs), side='left'))
MemoryError: Unable to allocate 6.58 TiB for an array with shape (904277555200,) and data type int64e 
```
-----------
```
  120     8 cells      16 cts       4 iterations  residual = 0.004618
/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py:1009: RuntimeWarning: divide by zero encountered in true_divide
  alpha = numpy.float32(rsold/pAp)
Traceback (most recent call last):
  File "/home/daniel/djl/code/CellModeller/Scripts/batch.py", line 54, in <module>
    main()
  File "/home/daniel/djl/code/CellModeller/Scripts/batch.py", line 50, in main
    simulate(moduleName, platnum, devnum)
  File "/home/daniel/djl/code/CellModeller/Scripts/batch.py", line 18, in simulate
    sim.step()
  File "/home/daniel/djl/code/CellModeller/CellModeller/Simulator.py", line 360, in step
    while not self.phys.step(self.dt): #neighbours are current here
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 569, in step
    if self.progress():
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 536, in progress
    if self.tick(self.actual_dt):
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 601, in tick
    self.sub_tick_init(dt)
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 583, in sub_tick_init
    self.update_grid() # we assume local cell_centers is current
  File "/home/daniel/djl/code/CellModeller/CellModeller/Biophysics/BacterialModels/CLBacterium.py", line 707, in update_grid
    self.grid_x_min = int(math.floor(min_x_coord / self.grid_spacing))
ValueError: cannot convert float NaN to integer
```
I don't have much experience programming with OpenCL but my intuition is that something is going wrong in the underlying OpenCL calls. Certainly something is very wrong when the code tries to initialize arrays with shape (904277555200,).

**Comment by timrudge** [comment] 2020-11-17 13:14
Which hardware/OS have you tried running on? Also when you say re-install you mean via pip?

**Comment by odanieloliveira** [comment] 2020-11-17 14:03
On my side, I tried running my model overnight and it seems to be working fine now. I'll keep an eye on the issue and let you know if it returns again. Thanks for the help!

**Comment by danieljones333** [comment] 2020-11-17 15:20
> Also when you say re-install you mean via pip?

Yes, I ran 'pip install -e . ' .

> Which hardware/OS have you tried running on?

My laptop is running Linux Mint 19.1 with an Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz and Intel Corporation HD Graphics 620. I've tried running with two different OpenCL drivers: the CPU-based  ["pocl" driver](http://portablecl.org/) as well as the ["Neo"](https://github.com/intel/compute-runtime) driver from Intel for the integrated graphics card. Interestingly, with the pocl driver I'm able to run Tutorial_1a.py for a few hundred iterations before crashing (as described above) whereas with the Neo driver the simulation crashes immediately.

I don't have access to the other workstation right now but it is running Ubuntu 18.04 with an Nvidia graphics card - I can get back to you with more details later.

**Comment by avimanyu786** [comment] 2020-12-20 17:06
Glad it helped you @odanieloliveira !

@danieljones333 @timrudge I switched to the dev branch from inside the docker container but unfortunately the issue still persists. Also tried installing the intel opencl runtime via the `intel-opencl` ppa(within the container) but still got similar results. Could it have something to do with the `if not` revisions(based on [2to3](https://docs.python.org/3/library/2to3.html)) in the `divide_cell` function of [CLBacterium.py](https://github.com/HaseloffLab/CellModeller/blob/dev/CellModeller/Biophysics/BacterialModels/CLBacterium.py)? It differs from the Python 2 version where this issue wasn't there.

**Comment by avimanyu786** [comment] 2021-01-22 15:45
Can confirm with the 1050 Ti that apparently, commit https://github.com/danilexn/CellModeller/commit/ae4eb610300c3f64d88e2445b83016ab7e6d066c fixes this issue..was able to run Tutorial_1a.py just fine upto 10,000 cells. Kudos to @danilexn!

**Comment by timrudge** [comment] 2021-04-01 13:04
Hi @avimanyu786 is this issue resolved now?

**Comment by avimanyu786** [comment] 2021-04-01 14:40
> Hi @avimanyu786 is this issue resolved now?

@timrudge

Yes Sir. https://github.com/HaseloffLab/CellModeller/pull/29 fixed it 😄.

**Closed** 2021-04-01 14:47 UTC
